x1 = int(input("Enter x co ordinate of 1st vertex:"))
y1 = int(input("Enter y co ordinate of 1st vertex:"))
x2 = int(input("Enter x co ordinate of 2nd vertex:"))
y2 = int(input("Enter y co ordinate of 2nd vertex:"))
area = (x2 - x1)*(y2-y1)
print("Area: ",area)
